config/routes.rb
Rails.application.routes.draw do
  
  resources :social_events
  resources :trainers
  resources :class_schedules

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

  get "prepare" => "home#prepare"

  get "contact_us" => "home#contact_us"

  get "cafe" => "home#cafe"

  resources :users do
    resources :user_workouts
    resources :user_meals
  end
  resource :session, only: [:new, :create, :destroy]

  resources :workouts do
    resources :user_workouts

    #resources :user_workouts do
      # put :approving
      # put :rejecting
    #end
  end

  resources :user_workouts

  resources :food_items do
    get "order_by_price" => "user_meals#order_by_price"
    get "order_by_meal_count" => "user_meals#order_by_meal"
  end

  resources :user_meals


end

app/models/user.rb
class User < ApplicationRecord
    #Associations

    #As trainee
    has_many :user_workouts, dependent: :destroy
    has_many :booked_workouts, through: :user_workouts, source: :workout
    
    #As trainer
    has_many :workouts, through: :user_workouts, dependent: :destroy

    #As admin
    has_many :social_events, dependent: :nullify
    has_many :class_schedules, dependent: :nullify
    has_many :trainers, dependent: :nullify

    # before_save :capitalize_name
    before_validation :set_default_role
    before_validation :set_default_meals
    before_validation :set_default_food_account

    #Validations
    validates :email, presence: true, uniqueness: true,
    format: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

    has_secure_password

    validates :first_name, presence: true
    validates :last_name, presence: true

    validates :meals, numericality: {greater_than_or_equal_to: 0}

    def full_name
        "#{first_name} #{last_name}"
    end

    private

    def capitalize_name
        self.first_name.capitalize!
        self.last_name.capitalize!
    end

    def set_default_role
        self.role ||= "guest"
    end

    def set_default_meals
        self.meals ||= 0
    end

    def set_default_food_account
        self.food_account ||= 0.00
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:edit,:update, :destroy]
    before_action :authorize!, only: [:index, :create, :edit, :update, :destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new user_params
        if @user.save
            redirect_to root_path
        else
            render :new
        end             
    end

    def show
        @users = User.all
        @user = current_user
        # if user is trainer
        @trainer_workouts = Workout
        .where(user_id:@user.id)
        .order(start_time: :ASC)
        # if user is guest
        @guest_workouts = UserWorkout.where(user_id: @user.id) 
    end

    def index
        @users = User.all
    end

    def edit    
    end

    def update
        if @user.update user_params
            flash[:notice] = 'Updated Successfully'
            redirect_to users_path
        else
            render :edit
        end
    end

    def destroy
        @user.destroy
        flash[:notice] = 'User successfully deleted.'
        redirect_to users_path
    end

    private

    def user_params
        params.require(:user).permit(
        :first_name, :last_name, :email, :password, :password_confirmation, :program, :meals, :food_account, :role
        )
    end

    def find_user
        @user = User.find params[:id]
        if @user === nil
            redirect_to root_path, notice: "User Does Not Exist"
        end
    end

    def authorize!
        unless can?(:crud, @user)
            redirect_to root_path, alert: 'Not Authorized'
        end
    end

end

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |f| %>

    <% if @user.errors.any? %>
        <p>
        <%= @user.errors.full_messages.join(', ') %>
        </p>
    <% end %>

    <div>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
    </div>
    <div>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
    </div>
    <div>
        <%= f.label :email%>
        <%= f.email_field :email %>
    </div>
    <div>
        <%= f.label :role %>
        <%= f.text_field :role %>
    </div>
    <div>
        <%= f.label :program %>
        <%= f.text_field :program %>
    </div>
    <div>
        <%= f.label :meals %>
        <%= f.text_field :meals %>
    </div>
    <div>
        <%= f.label :food_account %>
        <%= f.text_field :food_account %>
    </div>
    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>

    <%= f.submit "Sign Up" %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<% if can? :crud, @users %>
    <% @users.each do |user| %>
        <div>
            <h2><%= user.full_name %></h2>
            <button><%= link_to 'Edit', edit_user_path(user) %></button>
            <button><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        </div>
    <% end %>
<% end %>

app/views/users/new.html.erb
<h1>Please sign up</h1>

<%= form_with model: @user, local: true do |f| %>
    <% if @user.errors.any? %>
        <p>
        <%= @user.errors.full_messages.join(', ') %>
        </p>
    <% end %>

    <div>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
    </div>
    <div>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
    </div>
    <div>
        <%= f.label :email%>
        <%= f.email_field :email %>
    </div>
    <div>
        <%= f.label :role %>
        <%= f.text_field :role %>
    </div>
    <div>
        <%= f.label :program %>
        <%= f.text_field :program %>
    </div>
    <div>
        <%= f.label :meals %>
        <%= f.text_field :meals %>
    </div>
    <div>
        <%= f.label :food_account %>
        <%= f.text_field :food_account %>
    </div>
    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>

    <%= f.submit "Sign Up" %>

<% end %>

app/views/users/show.html.erb
    <h1> <%= icon('fas', 'user') %> <%= @user.full_name %></h1>
    <h3 class="meals">Meals left: <%= @user.meals %></h3>
    <h3 class="food-account">Food Account: <%= number_with_precision(@user.food_account, :precision => 2) %> thb (owing)</h3>
    

    <% if @guest_workouts.length > 0 %>
        <h3 class="booked">Booked Workouts</h3>
        <% @guest_workouts.each do |user_workout| %>
            <p><%= user_friendly_range(user_workout.workout.start_time) %> to <%= readable_time(user_workout.workout.end_time) %> with <%= user_workout.workout.user.first_name %></p>
        <hr>
        <% end %>
    <% end %>
    
    <% if @trainer_workouts.length > 0 %>
        <h3 class="booked">My Booked Workouts:</h3>
        <% @trainer_workouts.each do |workout| %>
            <% if !workout.user_workouts.empty? %> 
                <% workout.user_workouts.each do |guest_workout| %>
                <div>
                    <p><%= user_friendly_range(workout.start_time) %> to <%= readable_time(workout.end_time) %> with <%= guest_workout.user.first_name %></p>
                    <hr>
                    <%= link_to 'Edit', edit_workout_path(workout.id)%>
                    <br />
                    <%= link_to "Delete", workout_path(workout), method: :delete, data:{confirm:'Are you sure?' } %>
                    <hr>
                    <br />
                </div>
                <% end %>
            <% end %>
        <% end %>
    <% end%>
    
    <% if @trainer_workouts.length > 0 %>
        <h3 class="available">My Available Workouts:</h3>
        <% @trainer_workouts.each do |workout| %>
            <% if workout.user_workouts.empty? %> 
                <div>
                    <p><%= user_friendly_range(workout.start_time) %> to <%= readable_time(workout.end_time) %></p>
                    <hr>
                    <%= link_to 'Edit', edit_workout_path(workout.id)%>
                    <br />
                    <%= link_to "Delete", workout_path(workout), method: :delete, data:{confirm:'Are you sure?' } %>
                    <hr>
                    <br />
                </div>
            <% end %>
        <% end %>
    <% end%>