config/routes.rb
Rails.application.routes.draw do
  
  resources :social_events
  resources :trainers
  resources :class_schedules

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

  get "prepare" => "home#prepare"

  get "contact_us" => "home#contact_us"

  get "cafe" => "home#cafe"

  resources :users do
    resources :user_workouts
    resources :user_meals
  end
  resource :session, only: [:new, :create, :destroy]

  resources :workouts do
    resources :user_workouts

    #resources :user_workouts do
      # put :approving
      # put :rejecting
    #end
  end

  resources :user_workouts

  resources :food_items do
    get "order_by_price" => "user_meals#order_by_price"
    get "order_by_meal_count" => "user_meals#order_by_meal"
  end

  resources :user_meals


end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  #Assiociations
  has_many :user_meals
  belongs_to :section

  #Custom methods
  scope :search, lambda { |query|
  where("name ILIKE '%#{query}%' OR description ILIKE '%#{query}%'")
    .order(
      # Order first by food item whose name contains the `query`
      "name ILIKE '%#{query}%' DESC",
      # Then, if a food item's name and description contain the `query`,
      # put food items whose descriptions also contain the `query` later in results
      "description ILIKE '%#{query}%' ASC"
    )
  }

end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_food_item, only: [:show, :edit,:update, :destroy]
    before_action :authorize!, only: [:create, :edit, :update, :destroy]
    
    def index
        @sections = Section.all
        
        if params[:section]
            @section = Section.find_by_name params[:section]
            @food_items = FoodItem.where(section_id: @section.id.to_s)
        else
            @food_items = FoodItem.all
        end

        if params[:search]
            @food_items = @food_items.search(params[:search])
        end
      
        if params[:sort]
            if params[:dir]
              @dir = params[:dir]
            else
              @dir = 'asc'
            end
            @food_items = @food_items.order("#{params[:sort]} #{@dir}")
        end
      
    end

    # GET /food_items/1
    # GET /food_items/1.json
    def show
    end

    # GET /food_items/new
    def new
        @food_item = FoodItem.new
    end

    # GET /food_items/1/edit
    def edit
    end

    # POST /food_items
    # POST /food_items.json
    def create
        @food_item = FoodItem.new(food_item_params)
        respond_to do |format|
        if @food_item.save
            format.html { redirect_to @food_item, notice: 'food_item was successfully created.' }
            format.json { render :show, status: :created, location: @food_item }
        else
            format.html { render :new }
            format.json { render json: @food_item.errors, status: :unprocessable_entity }
        end
        end
    end

    # PATCH/PUT /food_items/1
    # PATCH/PUT /food_items/1.json
    def update
        respond_to do |format|
        if @food_item.update(food_item_params)
            format.html { redirect_to @food_item, notice: 'food_item was successfully updated.' }
            format.json { render :show, status: :ok, location: @food_item }
        else
            format.html { render :edit }
            format.json { render json: @food_item.errors, status: :unprocessable_entity }
        end
        end
    end

    # DELETE /food_items/1
    # DELETE /food_items/1.json
    def destroy
        @food_item.destroy
        flash[:notice] = 'Food Item successfully deleted.'
        redirect_to food_items_path
    end

    private

    # Only allow a list of trusted parameters through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :meal_number, :image_url, :section_id, :id)
    end

    def find_food_item
        @food_item = FoodItem.find params[:id]
        if @food_item === nil
            redirect_to root_path, notice: "Food Item Does Not Exist"
        end
    end

    def authorize!
        unless can?(:crud, @food_item)
            redirect_to root_path, alert: 'Not Authorized'
        end
    end

end

app/views/food_items/_control_row.html.erb
<!-- Control row -->
<div class="text-center">
  <%= form_tag nil, method: 'get' do %>
    <% if !params[:section].nil? %>
      <%= hidden_field_tag :section, params[:section] %>
    <% end %>
      <%= select_tag :sort, options_for_select([['Name', 'name'], ["Price", 'price']]) %>
      <%= select_tag :dir, options_for_select([['Asc', 'asc'], ["Desc", 'desc']]) %>
      
      <div id="sort">
      <%= submit_tag "Sort", :name => nil %>
      </div>
      
  <% end %>
</div>
<!-- End control row -->

app/views/food_items/_food_item.html.erb
<div>
    
      <% if food_item.image_url != "" %>
        <%= image_tag food_item.image_url, alt: 'food_item-image', class: 'food_item' %>
      <% end %>
      <h2><%= food_item.name %></h2>
      <p><%= food_item.description %></p>
      <p>Price: <%= number_with_precision(food_item.price, :precision => 2) %> thb</p>
      <p>Meal Count: # <%= food_item.meal_number %></p>
      <button><%= link_to 'Order by Price', food_item_order_by_price_path(food_item, @user_meal), data: { confirm: 'Are you sure? This will be added to your account.' } %></button>
      <button><%= link_to 'Order by Meal Count', food_item_order_by_meal_count_path(food_item, @user_meal), data: { confirm: 'Are you sure? This will be subtracted from your Meal Count.' } %></button>
      <% if can? :crud, food_item %>
        <button><%= link_to 'Edit', edit_food_item_path(food_item) %></button>
        <button><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></button>
      <% end %>
</div>

app/views/food_items/_form.html.erb
<%= form_with(model: food_item, local: true) do |form| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
        <% food_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label "Picture" %>
    <%= form.text_field :image_url %>
  </div> 
  <div>
    <%= form.label :section %>
    <%= form.text_field :section_id %>
  </div> 
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.label :meal_number %>
    <%= form.text_field :meal_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/food_items/_menu_content.html.erb
<div class="mu-tab-content-area">
  <div class="row">
    <% if @food_items.size == 0 %>
      <p class="text-center"> No item to display</p>
    <% else %>
      <% @food_items_split = @food_items.in_groups_of((@food_items.size/2.0).ceil, false) %>
      <div class="col-md-6">
        <ul class="mu-menu-item-nav">
          <% @food_items_split[0].each do |food_item| %>
            <%= render "food_item", food_item: food_item%>
          <% end %>
        </ul>
      </div>

      <% if @food_items_split.size > 1 %>
        <div class="col-md-6">
          <ul class="mu-menu-item-nav">
            <% @food_items_split[1].each do |food_item| %>
              <%= render "food_item", food_item: food_item%>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/food_items/_navbar.html.erb
<!-- Start navbar -->
<ul class="nav nav-tabs mu-restaurant-menu">
  <li>
  <div class="dropdown">
  <button class="dropbtn">Menu Sections</button>
    <div class="dropdown-content">
      <a><%= link_to 'ALL', food_items_path, class: "nav-link #{'active' if params[:section].nil?}" %></a>
      <% @sections.each do |section| %>
        <a><%= link_to section.name, food_items_path(section: section.name),
            class: "nav-link #{'active' if params[:section] == section.name}" %></a>
      <% end %>
    </div>
  </div>

  <div class="container search">
      <%= form_tag nil, method: 'get' do %>
        <div class="search-food">
        <%= text_field_tag :search, params[:search], placeholder: "Search" %>
        </div>
        <%= button_tag(:id =>'search-button', placeholder: "Search" ) do %>
          <i class="button" name="button"><%= icon('fas', 'search') %></i>
        <% end %>
      <% end %>
  </div>
  </li>
</ul>
<!-- End navbar -->

app/views/food_items/edit.html.erb
<h1>Edit Form</h1>
<%= render 'form', food_item: @food_item %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<!-- Start Restaurant Menu -->
<section id="mu-restaurant-menu">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="mu-restaurant-menu-area">
          <div class="mu-title">
            <span class="mu-subtitle">
                <h1><%= icon('fas', 'utensils') %> Food</h1>
                <h3>Cafe hours: 8am to 8pm</h3>
                <h3>Usual order wait time: 20min+</h3>
                <button><%=  icon('fas', 'info-circle') %> <%= link_to 'Cafe Info', "cafe" %></button>
                <h1><%= icon('fas', 'clipboard-list') %> Menu</h1>
            </span>
          </div>
          <div class="mu-restaurant-menu-content">
            <%= render "navbar" %>
            <%= render "control_row" %>
            <%= render "menu_content" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" frameborder="0"></iframe>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!-- /.modal -->
<!-- End Restaurant Menu -->

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>