config/routes.rb
Rails.application.routes.draw do
  
  resources :social_events
  resources :trainers
  resources :class_schedules

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

  get "prepare" => "home#prepare"

  get "contact_us" => "home#contact_us"

  get "cafe" => "home#cafe"

  resources :users do
    resources :user_workouts
    resources :user_meals
  end
  resource :session, only: [:new, :create, :destroy]

  resources :workouts do
    resources :user_workouts

    #resources :user_workouts do
      # put :approving
      # put :rejecting
    #end
  end

  resources :user_workouts

  resources :food_items do
    get "order_by_price" => "user_meals#order_by_price"
    get "order_by_meal_count" => "user_meals#order_by_meal"
  end

  resources :user_meals


end

app/models/trainer.rb
class Trainer < ApplicationRecord
    #Associations
    belongs_to :user

    #Validations
    validates :description, presence: true, length: {minimum: 3}
    validates :name, presence: true

end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]
  before_action :authorize!, only: [:create, :edit, :update, :destroy]
  
  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)
    @trainer.user = current_user
    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trainer_params
      params.require(:trainer).permit(:image_url, :name, :description)
    end

    def authorize!
      unless can?(:crud, @trainer)
          redirect_to root_path, alert: 'Not Authorized'
      end
    end

end

app/views/trainers/_form.html.erb
<%= form_with(model: trainer, local: true) do |form| %>
  <% if trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
        <% trainer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label "Picture" %>
    <%= form.text_field :image_url %>
  </div>
    
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Editing Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= icon('fas', 'users') %> Trainers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainers.each do |trainer| %>
      <div>
        <% if trainer.image_url != "" %>
          <%= image_tag trainer.image_url, alt: 'trainer-image', class: 'trainer' %>
        <% end %>
        <h2><%= trainer.name %></h2>
        <p><%= trainer.description %></p>
        <% if can? :crud, trainer %>
            <%= link_to 'Edit', edit_trainer_path(trainer) %>
            <%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %>  
        <% end %>
      </div>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :crud, @trainers %>
  <%= link_to 'New Trainer', new_trainer_path %>
<% end %>

app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Back', trainers_path %>