config/routes.rb
Rails.application.routes.draw do
  
  resources :social_events
  resources :trainers
  resources :class_schedules

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

  get "prepare" => "home#prepare"

  get "contact_us" => "home#contact_us"

  get "cafe" => "home#cafe"

  resources :users do
    resources :user_workouts
    resources :user_meals
  end
  resource :session, only: [:new, :create, :destroy]

  resources :workouts do
    resources :user_workouts

    #resources :user_workouts do
      # put :approving
      # put :rejecting
    #end
  end

  resources :user_workouts

  resources :food_items do
    get "order_by_price" => "user_meals#order_by_price"
    get "order_by_meal_count" => "user_meals#order_by_meal"
  end

  resources :user_meals


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fit-In</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= favicon_link_tag asset_path('logo.jpg') %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
  </head>

  <body>
  
    <!--<div class="container">-->

      <div class="menu-wrap">
        <input type="checkbox" class="toggler" />
        <div class="hamburger"><div></div></div>
        <div class="menu">
          <div>
            <div>
              <ul>
                <li><%= icon('fas', 'exclamation-triangle') %><%= link_to 'Prepare', prepare_path %></li>
                <li><%= icon('fas', 'mobile-alt') %><%= link_to 'Contact Us', contact_us_path %></li>
                <li><%= icon('fas', 'users') %><%= link_to 'Trainers', trainers_path %><li>
                <li><%= icon('fas', 'hiking') %><%= link_to 'Social Events', social_events_path %></li>
                <% if user_signed_in? && current_user.is_admin? %>
                  <li><%= icon('far', 'calendar-plus') %><%= link_to 'New Class', new_class_schedule_path %></li>
                  <li><%= icon('fas', 'utensils') %><%= link_to 'New Food Item', new_food_item_path %></li>
                  <li><%= icon('fas', 'receipt') %><%= link_to 'All Orders', user_meals_path %></li>
                  <li><%= icon('fas', 'user-plus') %><%= link_to "New User", new_user_path %></li>
                <% end %>
                <% if user_signed_in? && !current_user.is_admin? %>
                  <li><%= icon('fas', 'user') %><%= link_to 'My Profile', "/users/user.id" %></li>
                  <li><%= icon('fas', 'shopping-cart') %><%= link_to 'My Orders', user_meals_path %></li>
                <% end %>
                <% if user_signed_in?%>
                  <li><%= icon('fas', 'sign-out-alt') %><%= link_to "Sign Out", session_path, method: :delete,
                      data: {confirm: "Are you sure you want to sign out?"} %>
                  </li>
                <% else %>
                  <li><%= icon('fas', 'sign-in-alt') %><%= link_to "Sign In", new_session_path %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <nav>
        <div class="logo">
          <h1 class="main-logo"> <%= link_to image_tag("cut_logo.jpg"), root_path, { class: "navbar-link"} %> </h1>
          <p>Fit-In more time for fun. <br> Book. Order. Go! <%=icon('fas', 'running')%></p>
        </div>
        <p>
          <% flash.each do |type, message| %>
            <div class="flash flash-<%= type %>">
              <%= message %>
            </div>
          <% end %>
        </p>
        <div class="main-nav">
          <% if user_signed_in? %>
            <h5>Hello <%= current_user.full_name %></h5>
            
            <button><%= icon('fas', 'dumbbell') %> <%= link_to 'My Workouts', user_workouts_path %></button>
            
            <button><%= icon('fas', 'utensils') %> <%= link_to 'Food', food_items_path %></button>
            
            <button><%= icon('fas', 'calendar-alt') %> <%= link_to 'Available Workouts', workouts_path %></button>
            <% if current_user.role == "trainer" %>
              <button><%= icon('far', 'calendar-plus') %> <%= link_to 'New Session', new_workout_path %></button>
            <% end %>
            <% if current_user.is_admin? %>
              <button><%= icon('fas', 'users') %> <%= link_to 'Users', users_path %></button>
            <% end %>
          <% end %>
        </div>
      </nav>
      <%= yield %>
    <!--</div>-->
  </body>
</html>